---
- name: Add and update packages
  include: apt.yml

- name: Update Docker
  include: docker.yml

- name: Create dir ~/.kube
  file: path=/home/pirate/.kube state=directory owner=pirate group=users mode=0775

- name: Setup profile
  template: src=kubernetes_profile.sh dest=/etc/profile.d/kubernetes.sh mode=0644

- name: Install with kubeadm
  include: kubeadm.yml
