- name: Create Weave resource file
  template: src=cni/weave.yml dest=/etc/kubernetes/kube-weave.yml

- name: Create Weave resources
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  command: kubectl create -f /etc/kubernetes/kube-weave.yml

- name: Download cluster configuration
  fetch:
    src: "/etc/kubernetes/admin.conf"
    dest: "{{ playbook_dir }}/run/"
    flat: true
