- name: Add a group pirate
  group: name=pirate

- name: Add a group docker
  group: name=docker

- name: Add user pirate to group docker
  user: name=pirate groups=docker,pirate append=yes shell=/bin/bash

- name: Add pirate to to sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: "pirate ALL=(ALL) NOPASSWD: ALL"
    insertafter: "EOF"

- name: Verify ~/.ssh
  file: path="/home/pirate/.ssh" state=directory recurse=no owner=pirate group=pirate

- name: Copy SSH Key
  copy: src="{{ ssh.pub_key_path }}" dest=/home/pirate/.ssh/authorized_keys mode=0600 owner=pirate group=pirate

- name: Add user pirate to group docker
  user: name=pirate groups=docker append=yes

- name: Set user password
  user: name=pirate password="{{ user.password }}"
  when: user is defined and user.password is defined
